services:
  hoe-site:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # prevent host's empty node_modules from overwriting container's
    environment:
      - NODE_ENV=development
    command: npm run dev
